### ISSUE TITLE
TAR archives created by DART Runner have unexpected behavior

### ISSUE THREAD

**Issue by bonniegee** [APTrust/dart-runner#5]
The tarballs created by DART Runner behave differently than the tarballs created by DART (and other systems we use to create tarballs) when we’re unpacking them using Python’s tarfile library. When getting a list of the members of the archive, we are not seeing the directory as a member of the list—just the files and subdirectories.

**Comment by diamondap** [comment]
This should be fixed in v0.93-beta. See https://aptrust.github.io/dart-docs/users/dart_runner/#downloads for download links.
